method:
    name: "gaussian_process"
    mode: "sequential" # search_only, evaluate_only, sequential

hydra:
    run:
        dir: D:\\Users\\Julien\\Documents\\Diplom_Results\\experiments_da\\${method.name}