run:
    seed: 1111
    gpu: 0
    data: ???
    report_freq: 50

train:
    cutout: false
    batch_size: 128

search:
    search_space: pcdarts

architecture:
    zeta_eval: ???
    layers: 20 # number of cells the final network should be composed of
    auxiliary: true
    genotype: ???
    checkpoint: ???
