run:
    seed: 1111
    gpu: 0
    data: ???
    report_freq: 50
    checkpoint_path: ???

train:
    cutout: false
    batch_size: 128

search:
    search_space: pcdarts

architecture:
    layers: 20 # number of cells the final network should be composed of
    auxiliary: true
    
