train:
    scheduler: cosine
    lr_anneal_cycles: 1
    smooth_cross_entropy: false
    batch_size: 64 
    learning_rate: 0.1
    learning_rate_min: 0.0
    momentum: 0.9
    weight_decay: 0.0003
    init_channels: 16
    layers: 8   # number of cells the final network should be composed of
    cutout: false
    auxiliary: false # @see https://stats.stackexchange.com/questions/304699/what-is-auxiliary-loss-as-mentioned-in-pspnet-paper
    auxiliary_weight: 0.4
    drop_path_prob: 0
    grad_clip: 5


hydra:
    run:
        dir: /home/julienf/data/search-${search.search_space}-${search.method}-${run.dataset}-${run.seed}
    
    

  

